ansible:
  build: ./
  container_name: ansible
  hostname: ansible
  ports:
    - 80:80
  volumes:
    - /c/Users/atos/develop/etude01/var/www/html:/var/www/html
    - /c/Users/atos/develop/etude01:/home
  tty: true
