- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install httpd
      yum: name=httpd state=present
      notify:
        - restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
